### ISSUE TITLE
GET /ip_addresses, query parameter, service from port child-resource

### ISSUE THREAD

**Issue by asadoughi** [rackerlabs/quark#393]
The GET response handler doesn't seem to be responding to the service query parameter as a filter.

`GET /v2.0/ip_addresses.json?tenant_id=75ba27c9ac204c65a8141a25a4275fba&service=compute&device_id=acfae3a5-59d2-484c-aa46-7a738ad37154 HTTP/1.1` returns an ip_address where its related port has service equal to `none`.

**Comment by roaet** [comment]
The functionality was simply not built in due to misunderstanding.

**Comment by roaet** [comment]
Still doesn't make any sense to me. Why would I be filtering with a 'service' attribute on a ip_address entity? Same with device id. Just doesn't feel right at all.

**Comment by Cerberus98** [comment]
Feels like that should be hanging off port, no?

Service and device_id aren't IP columns, they're on port. So really what I want is a port owned by <tenant> attached to <device> associated with <service>

Thoughts?

**Comment by asadoughi** [comment]
As I've discussed with Justin in private previously, having `service` and `device_id` as query parameters off of `GET /ip_addresses` is an optimization to reduce the number of calls from nova to neutron from many to one. 

When a nova user invokes `GET /server/{serverId}/ip_associations` they require nova to ask neutron for all IPs associated with this server. The vanilla way for nova to do that would be `GET neutron:///ip_addresses?tenant_id={tenantId}` and for each of the returned IP addresses invoke `GET neutron:///ip_addresses/{ipAddressId}/ports?device_id={serverId}&service=compute`, effectively N + 1 calls where N is the number of IP addresses the tenant owns.

To optimize this down from N+1 to just one call, in the API we've specified that the port attributes `service` and `device_id` can be used as query parameters to filter the join of IPs and their associated ports.

Admittedly, it's not well-principled API design. I don't claim to be an API design expert. I'm open to hearing other ways in how we maintain API design principles yet keep the efficiency.

**Comment by Cerberus98** [comment]
I see, sorry. I'm also of the mindset that we should probably sacrifice some API sanity for performance.

Considering we're referencing attributes that don't belong to IPs in that query above, and Justin has referenced this before, but what about a new top level resource that was explicitly what you're looking for? /associated_ip_addresses or /serviced_ip_addresses

I'll be the first to admit that it ain't purty, but maybe it's simpler on top of accomplishing what you want? Just my 0.31 pesos

**Comment by roaet** [comment]
As a new resource it would be more 'correct' but it would also be a lot of work. It is of course possible to do it the proposed way but it will be a completely new logic branch if certain filters are there: weird.

**Comment by asadoughi** [comment]
Yeah, a new resource would be a lot more work. On the pro side for that case, this part of the shared IPs work is isolated between nova and neutron.

I'm not sure this is a completely new logic branch. A comparable implementation would be the `ip_address_id` filter on `port_find`. Similar to how `service` and `device_id` are not an IP address attribute, `ip_address_id` is not an attribute of a port.

**Comment by Cerberus98** [comment]
Fair enough. I don't want to create new work for people. Just wanted to throw out the idea :snowboarder:

**Comment by roaet** [comment]
There isn't a ip_address_id filter on the basic port find API interface. It is gained from the parent resource. Now it is definitely possible now to filter off it since the support was added but we can easily remove that sort of thing from the original port controller. 

I will add the filter logic to the ip controller.

**Comment by roaet** [comment]
Nevermind, I am dumb. All of things added happily.

**Comment by roaet** [comment]
Tested and completed. Will close when PR merges.
