### ISSUE TITLE
GET /v2.0/ip_addresses/{ipAddressId}/ports?device_id={deviceId} does not consider {ipAddressId}

### ISSUE THREAD

**Issue by asadoughi** [rackerlabs/quark#397]
`GET /v2.0/ip_addresses/194885e2-ad79-4ed4-b395-7f2f0d11764b/ports.json?device_id=add14ce8-17cc-4ce3-b6c4-c2d7d2a2d963` returns more than one port even though in the backend there is only one port given the specified ip_addresses id and device_id parameters. e.g.

```
curl -i http://neutron/v2.0/ip_addresses/194885e2-ad79-4ed4-b395-7f2f0d11764b
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 320
Date: Thu, 11 Jun 2015 19:57:20 GMT

{"ip_address": {"subnet_id": "8d68d551-8cd6-48d7-b77d-de54d96f8c92", "version": 4, "address": "10.13.20.33", "network_id": "00000000-0000-0000-0000-000000000000", "used_by_tenant_id": "9617287", "port_ids": ["20b7024a-f1be-47ce-b99c-7eba82dca19a"], "address_type": "fixed", "id": "194885e2-ad79-4ed4-b395-7f2f0d11764b"}}
```

Note, there are multiple ports associated with the device_id, but only one port on the device_id and ipAddressId pair.

**Comment by asadoughi** [comment]
As this bug was blocking the ongoing integration testing, I dug in and found that a change that worked was replacing `filters['ip_address'] = ip_id` with `filters['ip_address_id'] = [ip_id]`.

**Comment by roaet** [comment]
tested and fixed. will close with PR.
