### ISSUE TITLE
POST /v2.0/ip_addresses.json not working

### ISSUE THREAD

**Issue by asadoughi** [rackerlabs/quark#398]
I think the database layer suffered from bit rot from lack of use. Specifically, the look up of ports with `scope=db_api.ONE` does not work. I had to hotpatch the query to use `db_api.ALL` with the entire list of `port_ids` to `port_find` the requested ports.

**Comment by asadoughi** [comment]
An additional workaround: I had to manually flip the 'enabled' bit in the database as there is no way to enable the port-ip association via API that I can see.

**Comment by asadoughi** [comment]
After the POST /ports was hotpatched to create the resource, it appears that the GET /ports response is not returning the newly associated IP... . I'm still investigating. i.e. a publicnet port with a newly associated IP should have 3 IPs (not 2) and a servicenet port should have 2 IPs (not one).

**Comment by asadoughi** [comment]
Ah, apparently a shared IP is not considered a fixed IP https://github.com/rackerlabs/quark/blob/master/quark/plugin_views.py#L231

**Comment by roaet** [comment]
tested and fixed. will close with PR.
