### ISSUE TITLE
GET /ports does not return shared IPs as part of fixed_ips

### ISSUE THREAD

**Issue by asadoughi** [rackerlabs/quark#399]
https://github.com/rackerlabs/quark/blob/master/quark/plugin_views.py#L231
and 
https://github.com/rackerlabs/quark/blob/master/quark/plugin_views.py#L212

**Comment by roaet** [comment]
I feel like it is a bit of a miscommunication to put shared_ips there too. The name of the attribute *is* fixed_ips. Should we add another attribute called shared_ips? Will we just live with the ambiguity?

**Comment by asadoughi** [comment]
You bring up a good point regarding communication to the end user. 

The intention behind this issue is for Nova to understand it needs to add the shared IPs to the virtual interfaces associated with the Neutron ports.

To add onto your point, in the Neutron universe, there is no such thing as shared IPs, only fixed and floating IPs. So, in that worldview, I'd argue that a shared IP is a type of fixed IP.

**Comment by asadoughi** [comment]
Thinking about this more today, Nova's relationship with a fixed IP is actually different than that of shared IP. For example, I noticed when a fixed IP is removed from an instance it is also disassociated with Neutron port. This is not the expected behavior for shared IP: if it is removed from the instance, we still expect it to be associated with the Neutron port.

**Comment by asadoughi** [comment]
So, what worked for me in practice is to add `or (ip.get("address_type") == ip_types.SHARED and port.service != "none"))` to the highlighted clauses. What do you think? I'm not sure how this stands for the end user, but it fixes the nova-neutron relationship.

**Comment by roaet** [comment]
I still feel that it is ambiguously defined (shared or unshared) but I will make the change.

**Comment by roaet** [comment]
tested and fixed. will close with PR.
